import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import getTrains from "../helpers/getTrains";
import styles from "../styles/Home.module.css";
import { Trein } from "../types/getTrainsResponse";
import dynamic from "next/dynamic";
import getStations from "../helpers/getStations";
import {
  SmallStation,
  SmallStations,
  Station,
} from "../types/getStationsResponse";

export async function getServerSideProps() {
  const trains = await getTrains();
  const stations = await getStations();
  const { stations: smallStations } = new SmallStations(stations.payload);

  return {
    props: {
      trains: trains.payload.treinen,
      stations: smallStations,
    },
  };
}

const Home = ({
  trains,
  stations,
}: {
  trains: Trein[];
  stations: SmallStation[];
}) => {
  const MapWithNoSSR = dynamic(() => import("../components/Map"), {
    ssr: false,
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.leaflet}>
        <MapWithNoSSR trains={trains} stations={stations} />
      </main>
    </div>
  );
};

export default Home;
