import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import TrainMap from "../components/TrainMap";

const Home = () => {
  return (
    <div>
      <Head>
        <title>NS Spoorkaart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.leaflet}>
        <NavBar />
        <TrainMap />
      </main>
    </div>
  );
};

export default Home;
